content/dogepedia/articles/what-is-dogecoin.md
Can someone please make sure the links in the article point to what will be the correct URLs? 🙏
=> 'What is Dogecoin' Article

content/dogepedia/articles/who-owns-dogecoin.md
Please check whether links point to valid URL.
=> 'Who Owns and Controls Dogecoin' Article

content/dogepedia/articles/how-does-dogecoin-work.md
Links need checking. Not sure how to generate the second link, which is to the whole 'Community and Ecosystem' **subsection** (not a specific question/article/stub).
=> 'How Does Dogecoin Work' Article

content/dogepedia/articles/send-and-receive-dogecoin.md
Please ensure that the link is to a valid URL.
=> 'Send & Receive Dogecoin' Article

content/dogepedia/faq/dogecoin-is-a-joke.md
Really helpful content that I tweaked a bit MishaBoar. Please tweak/add/edit/delete however you see fit. :)
=> 'Dogecoin is a Joke' Article

content/dogepedia/articles/how-do-i-get-a-wallet.md
Please check links point to a valid URL. :)
=> 'How Do I Get a Wallet' Article

content/dogepedia/faq/dogecoin-has-no-developers.md
Link will need checking. Assuming that this will be the link for the Foundation website. As always, please edit wherever. Made a few tweaks - but still v much in line with original content.
=> 'Dogecoin has No Developers' Article

content/dogepedia.md
Add in-page links to Dogepedia page. See https://github.com/dogecoinfoundation/dogecoin.com/pull/20#discussion_r772778564
=> Add in-page links for Dogepedia index.

content/dogepedia/articles/merchants-accepting-doge.md
I've kept this one generalised for reasons mentioned in the article, but please feel free to change / add / edit / delete wherever.
=> 'Merchants Accepting Doge' Article

content/dogepedia/faq/dogecoin-and-coin-burning.md
=> 'Dogecoin & Coin Burning' Article

content/dogepedia/articles/what-is-a-node.md
This is very much a draft. A few things:
1. I'm not sure of the links 
2. Should we include what a full node is and why it’s beneficial? 
3. Although implicit, I think we can emphasise a bit more why running a node is important. Also, the second part of this article ('Do I need to run one?'), hasn't been explicitly answered.
=> DRAFT 'What is a Node' Article

content/dogepedia/articles/how-can-my-business-accept-dogecoin.md
Not sure whether it's worthwhile to end this article by flagging the Foundation's plans to develop a L2 POS app? For example:
The Dogecoin Foundation have also flagged [plans] (https://foundation.dogecoin.com/trailmap/prologue/) to develop a Point of Sale (POS) layer 2 application for merchants. Etc, etc.
=> Draft 'How can my Business Accept Dogecoin' Article

content/dogepedia/articles/dogecoin-developers.md
Suggestions for improvements most welcome. :)
=> 'Dogecoin Developers' Article

content/dogepedia/articles/becoming-a-dogecoin-developer.md
Suggestions for improvements are most welcome. :)
=> 'Becoming a Dogecoin Developer' Article

content/dogepedia/articles/what-is-a-blockchain.md, content/dogepedia/articles/what-is-a-miner.md, content/dogepedia/articles/what-is-a-mining-pool.md, content/dogepedia/articles/what-is-a-node.md
What is a miner article, first iteration. I had to make some modifications to "What is a blockchain" and "What is a node", also to allow cross-linking.
Very difficult to keep an ELI5 tone in this one (even though the process of simplification took really forever on this one), even though the first two paragraphs could be enough for a person not interested at going more in depth.
=> What is a miner, and related articles revisions

content/dogepedia/articles/dogecoin-developers.md
need to slow down, i missed broken link. apologies however is fixed in pr :)
=> fix broken link

content/dogepedia/articles/what-is-a-miner.md, content/dogepedia/how-tos/mining-dogecoin.md
How to Mine Dogecoin article.
I avoided mentioning specific hardware manufacturers, mining pools, and listing specific websites. This might be useful, but considering the amount of scams in the mining market, might be a tad risky to add in an article on the main dogecoin.com. If needed, we can change this and include some pools and some popular ASIC manufacturers.
=> How to mine and minor modifications

content/dogepedia/how-tos/mining-dogecoin.md
Just added a link to minerstat. I know we are (in this first iteration) not linking a lot to external sources, but I think in this case the benefits for the reader outweigh possible issues.
=> Added link to minerstat

content/dogepedia/how-tos/operating-a-node/index.md
Hey Richard, my colleague read the online article and pointed out a couple of minor issues and suggested I add more information about the RPC commands as well (I was already going to, but I was planning to do so in the days after the website launches).
=> Added RPC details. Minor typos fixed.

config.toml
=> remove baseURL

content/dogepedia/articles/how-does-dogecoin-work.md
Minor fixes and links to in-depth articles. Also adjusted image link to use absolute URL - we can do the same in other articles.
=> Minor adjustments and in-depth links

content/dogepedia/faq/dogecoin-whale-wallets.md
First iteration of the whale article.
=> Dogepedia - Whale hoarding 30% of the supply Article

content/dogepedia/faq/dogecoin-has-no-utility.md
Update (including fix suggested by Richard).
=> Dogepedia - Update dogecoin-has-no-utility.md

content/dogepedia/articles/how-can-my-business-accept-dogecoin.md
Typos and added more information about ecommerce solutions, with mentions to libdogecoin and DogeGarden.
=> Dogepedia - Update how-can-my-business-accept-dogecoin.md

content/dogepedia/articles/becoming-a-dogecoin-developer.md
Removed paragraph about Ross' streams.
=> Dogepedia - Update becoming-a-dogecoin-developer.md

content/dogepedia/articles/what-is-a-mining-pool.md
Fixed some typos and wording, and added a link to the ASICs section of the mining guide.
=> Dogepedia - Fixed typos and added linking.

content/en/dogepedia/articles/dogecoin-roadmap.md
brings in roadmap article content from former PR
=> Added content from former PR #31

package.json, themes/hello-friend-ng/assets/scss/_whatisdogecoin.scss, themes/hello-friend-ng/assets/scss/main.scss, themes/hello-friend-ng/layouts/dogepedia/list.html, themes/hello-friend-ng/layouts/index.html, themes/hello-friend-ng/layouts/partials/community.html, themes/hello-friend-ng/layouts/partials/head.html, themes/hello-friend-ng/layouts/partials/locale.html, themes/hello-friend-ng/layouts/partials/menu.html, themes/hello-friend-ng/layouts/partials/resources.html, themes/hello-friend-ng/layouts/partials/tablist_item.html, themes/hello-friend-ng/layouts/partials/whatisdogecoin.html, themes/hello-friend-ng/layouts/wallets/list.html
- Fixed right side "ghost margin"
- Fixed bouncing Doge wen text animation "the people's currency"
- Mobile Menu improvments for better navigation.
- Fixed Background on Home Steps on Dark Mode
- Fixed Social media buttons on Home, wen in Mobile mode
- Fixed "...about Dogecoin" cards size.
- Fixed Background on Wallets, on Dark Mode
- Removed some more files not needed.
=> Improvments

config.toml
=> Fix config bug

themes/hello-friend-ng/assets/scss/_dogepedia.scss
=> Fix responsive DataTables

CNAME
=> Update CNAME to dogecoin.com

CNAME, static/CNAME
Revert to preview.dogecoin.com
=> Revert to preview.dogecoin.com

CNAME, static/CNAME
=> Change to dogecoin.com

themes/hello-friend-ng/layouts/partials/head.html
=> Fix header url on cards

README.md, doc/how-to-get-website.md, doc/how-to-run-website.md, doc/how-to-translate-website.md
Removed the "Preview" from the Readme and fixed the npm installation guide
=> Fixed Readme Docs

themes/hello-friend-ng/layouts/index.html
Add header warning to tell shibes that a language is not full translated
=> Translation not finished warning

config.toml, i18n/pt-pt.toml
- Menu translation completed
- Main page Translation completed
=> Translation Portuguese from Portugal (partial)

content/de/dogepedia.md, content/de/dogepedia/articles/dogecoin-developers.md, content/en/dogepedia.md, content/en/dogepedia/articles/dogecoin-developers.md, content/es/dogepedia.md, content/es/dogepedia/articles/dogecoin-developers.md, content/fr/dogepedia.md, content/fr/dogepedia/articles/dogecoin-developers.md, content/kr/dogepedia.md, content/kr/dogepedia/articles/dogecoin-developers.md, content/no/dogepedia.md, content/no/dogepedia/articles/dogecoin-developers.md, content/pt-pt/dogepedia.md, content/pt-pt/dogepedia/articles/dogecoin-developers.md, content/th/dogepedia.md, content/th/dogepedia/articles/dogecoin-developers.md, content/zh-cn/dogepedia.md, content/zh-cn/dogepedia/articles/dogecoin-developers.md
Enable Dogecoin Developers Dogepedia article
=> Enable Dogecoin Developers Dogepedia article

content/en/resources.md
Removed additional credit - unnecessary and not in line with everything else listed here.
=> resources: make blockshibe listing uniform

content/de/resources.md, content/es/resources.md, content/fr/resources.md, content/kr/resources.md, content/no/resources.md, content/pt-pt/resources.md, content/th/resources.md, content/zh-cn/resources.md
updated remaining non english blockshibe listings in resources.md in congruence with 3c643b252.
=> resources: fix remaining blockshibe listings

content/de/contributors/Richard.md, content/en/contributors/Richard.md, content/es/contributors/Richard.md, content/fr/contributors/Richard.md, content/kr/contributors/Richard.md, content/no/contributors/Richard.md, content/pt-pt/contributors/Richard.md, content/th/contributors/Richard.md, content/zh-cn/contributors/Richard.md
=> Contributors fix

themes/hello-friend-ng/layouts/partials/head.html
Fix header SEO to be able to get better search engine results
=> Fix header SEO

content/zh-cn/dogepedia/articles/what-is-dogecoin.md
translate what-is-dogecoin.md into Chinese
=> translate what-is-dogecoin.md into Chinese

i18n/de.toml, i18n/en.toml, i18n/es.toml, i18n/fr.toml, i18n/gl.toml, i18n/hi.toml, i18n/it.toml, i18n/ja.toml, i18n/kr.toml, i18n/lmo.toml, i18n/ml.toml, i18n/pt-br.toml, i18n/pt-pt.toml, i18n/ro.toml, i18n/ru.toml, i18n/tr.toml, i18n/uk.toml, i18n/zh-cn.toml, i18n/zh-hk.toml, i18n/zh-tw.toml, themes/hello-friend-ng/layouts/index.html, themes/hello-friend-ng/layouts/partials/head.html, themes/hello-friend-ng/layouts/partials/menu.html
Added DogecoinSwag and Core Upgrade warning
=> DogeSwag and Core Upgrade Warning

content/zh-cn/dogepedia/articles/how-does-dogecoin-work.md
translate how-does-dogecoin-work.md into Chinese
=> translate how-does-dogecoin-work.md into Chinese

content/zh-cn/dogepedia/articles/get-dogecoin.md
translate get-dogecoin.md into Chinese
=> translate get-dogecoin.md into Chinese

content/zh-cn/dogepedia.md
translate dogepedia.md into Chinese
=> translate dogepedia.md into Chinese

themes/hello-friend-ng/assets/scss/_normalize.scss
Fix Dogepedia links https://github.com/dogecoinfoundation/dogecoin.com/issues/153
=> Fix Dogepedia Links #153

content/de/wallets/Ledger.md, content/en/wallets/Ledger.md, content/es/wallets/Ledger.md, content/fr/wallets/Ledger.md, content/kr/wallets/Ledger.md, content/no/wallets/Ledger.md, content/pt-pt/wallets/Ledger.md, content/th/wallets/Ledger.md, content/zh-cn/wallets/Ledger.md
[Fix ](https://github.com/dogecoinfoundation/dogecoin.com/issues/176)
Fix Ledget Wallet link
https://github.com/dogecoinfoundation/dogecoin.com/issues/176
=> Fix Ledger Wallet link https://github.com/dogecoinfoundation/dogecoin.com/issues/176

themes/hello-friend-ng/layouts/index.html
Added link to the home page Dogecoin Core Wallet upgrade.
=> Dogecoin Core Wallet Upgrade llink

content/de/wallets/AtomicWallet.md, content/en/wallets/AtomicWallet.md, content/es/wallets/AtomicWallet.md, content/fr/wallets/AtomicWallet.md, content/kr/wallets/AtomicWallet.md, content/no/wallets/AtomicWallet.md, content/pt-pt/wallets/AtomicWallet.md, content/th/wallets/AtomicWallet.md, content/zh-cn/wallets/AtomicWallet.md
=> Added Atomic Wallet

content/de/wallets/AtomicWallet.md, content/en/wallets/AtomicWallet.md, content/es/wallets/AtomicWallet.md, content/fr/wallets/AtomicWallet.md, content/kr/wallets/AtomicWallet.md, content/no/wallets/AtomicWallet.md, content/pt-pt/wallets/AtomicWallet.md, content/th/wallets/AtomicWallet.md, content/zh-cn/wallets/AtomicWallet.md
AyomicWallet - Removed Opensource Tag
=> AtomicWallet - Removed Opensource Tag

doc/how-to-translate-website.md
Improvment on translation documents
=> Improvment on translation documents

themes/hello-friend-ng/layouts/dogeathon/list.html, themes/hello-friend-ng/layouts/partials/dogeathon_blocks.html
=> Fix some mobile issues

themes/hello-friend-ng/layouts/partials/dogeathon_blocks.html
=> fixed colors

content/de/wallets/Guarda.md, content/en/wallets/Guarda.md, content/es/wallets/Guarda.md, content/fr/wallets/Guarda.md, content/kr/wallets/Guarda.md, content/no/wallets/Guarda.md, content/pt-pt/wallets/Guarda.md, content/th/wallets/Guarda.md, content/zh-cn/wallets/Guarda.md
=> Guarda Wallet

themes/hello-friend-ng/layouts/dogeathon/list.html, themes/hello-friend-ng/layouts/partials/dogeathon_blocks.html, themes/hello-friend-ng/layouts/partials/menu.html
=> Added Dogeathon Teams

themes/hello-friend-ng/layouts/dogeathon/list.html
Add Team Link on new windows fix
=> Teams Link on new windows fix

themes/hello-friend-ng/layouts/wallets/list.html
Remove any ratings wallets asked by some members of the comunity on Twitter.
=> Remove any ratings wallets

themes/hello-friend-ng/layouts/wallets/list.html
=> Randomly display wallets

content/de/wallets/exodus.md, content/en/wallets/exodus.md, content/es/wallets/exodus.md, content/fr/wallets/exodus.md, content/kr/wallets/exodus.md, content/no/wallets/exodus.md, content/pt-pt/wallets/exodus.md, content/th/wallets/exodus.md, content/zh-cn/wallets/exodus.md, content/zh-tw/wallets/exodus.md
=> Added exodus wallet

content/de/wallets/ThorWallet.md, content/en/wallets/ThorWallet.md, content/es/wallets/ThorWallet.md, content/fr/wallets/ThorWallet.md, content/kr/ThorWallet.md, content/no/wallets/ThorWallet.md, content/pt-pt/wallets/ThorWallet.md, content/th/wallets/ThorWallet.md, content/zh-cn/wallets/ThorWallet.md, content/zh-tw/wallets/ThorWallet.md
=> Added THORWallet

themes/hello-friend-ng/layouts/dogeathon/list.html
=> Dogeathon-live-fix

themes/hello-friend-ng/layouts/dogeathon/list.html
=> Live Dogeathon 3

themes/hello-friend-ng/layouts/dogeathon/list.html
=> Dogeathon remove live 3

themes/hello-friend-ng/layouts/dogeathon/list.html
=> Dogeathon live 4

themes/hello-friend-ng/layouts/dogeathon/list.html
=> Dogeathon Live Demos

themes/hello-friend-ng/layouts/dogeathon/list.html, themes/hello-friend-ng/layouts/partials/dogeathon_blocks.html
=> Dogeathon end

themes/hello-friend-ng/layouts/index.html, themes/hello-friend-ng/layouts/partials/menu.html
Removed Kabosu Birthday and Hackathon links
=> Remove Kabosu Birthday

content/en/trademarks.md
This reverts commit 9072f4fd457e11b17988e5f1818cbe8ac4dba967.
This repo is configured with merge rules which are fairly simple:
* anyone can raise a PR
* PR must be approved by 1 other person 
^ This has been explained to every contributor
Using admin privileges to bypass the repository rules should obviously only ever be used in an extreme emergency, ie: preventing an exploitable bug etc.
=> Revert "Added some historical information"

content/de/wallets/AmmerWallet.md, content/en/wallets/AmmerWallet.md, content/es/wallets/AmmerWallet.md, content/fr/wallets/AmmerWallet.md, content/no/wallets/AmmerWallet.md, content/pt-pt/wallets/AmmerWallet.md, content/th/wallets/AmmerWallet.md, content/zh-cn/wallets/AmmerWallet.md, content/zh-tw/wallets/AmmerWallet.md
=> Add Ammer Wallet

content/de/wallets/DogepartyWallet.md, content/en/wallets/DogepartyWallet.md, content/es/wallets/DogepartyWallet.md, content/fr/wallets/DogepartyWallet.md, content/no/wallets/DogepartyWallet.md, content/pt-pt/wallets/DogepartyWallet.md, content/th/wallets/DogepartyWallet.md, content/zh-cn/wallets/DogepartyWallet.md, content/zh-tw/wallets/DogepartyWallet.md
Referring to https://github.com/dogecoinfoundation/dogecoin.com/issues/288
=> XDP Wallet Change to DogeWallet (DogeParty Wallet)

content/de/dogepedia/articles/how-can-i-help-doge.md, content/en/dogepedia/articles/how-can-i-help-doge.md, content/es/dogepedia/articles/how-can-i-help-doge.md, content/fr/dogepedia/articles/how-can-i-help-doge.md, content/no/dogepedia/articles/how-can-i-help-doge.md, content/pt-pt/dogepedia/articles/how-can-i-help-doge.md, content/th/dogepedia/articles/how-can-i-help-doge.md, content/zh-cn/dogepedia/articles/how-can-i-help-doge.md, content/zh-tw/dogepedia/articles/how-can-i-help-doge.md, themes/hello-friend-ng/layouts/partials/community.html
=> Updated Discord URL

content/de/wallets/EdgeWallet.md, content/en/wallets/EdgeWallet.md, content/es/wallets/EdgeWallet.md, content/fr/wallets/EdgeWallet.md, content/no/wallets/EdgeWallet.md, content/pt-pt/wallets/EdgeWallet.md, content/th/wallets/EdgeWallet.md, content/zh-cn/wallets/EdgeWallet.md, content/zh-tw/wallets/EdgeWallet.md
Edge is a non-custodial multi-currency wallet that supports the top cryptocurrencies and tokens including DOGE. Edge has established itself to be one of the longest standing self-custody solutions in addition to being fully an open-source. Source can be found on Edge's GitHub repo: https://github.com/EdgeApp/edge-react-gui
Edge Wallet is available as a mobile wallet (iOS & Android). More information can be found on the official website: https://edge.app
=> Add Edge to wallet list

content/de/resources.md, content/en/resources.md, content/es/resources.md, content/fr/resources.md, content/no/resources.md, content/pt-pt/resources.md, content/th/resources.md, content/zh-cn/resources.md, content/zh-tw/resources.md
Removed ShopDoge.xyz (is now ad page for adult content)
=> Outdated link in resources

config.toml, content/en/dogeathon/_index.md, themes/hello-friend-ng/layouts/dogeathon-2025/list.html, themes/hello-friend-ng/layouts/partials/external_menu.html
- Added Register Button
- Added Hackathons old Videos and Button
- Added Social Media Share Card with image and description
- Fixed Meta Tag Title
- Removed weekend because its a on week days and not on a weekend
=> Some Engagments

content/de/wallets/ShapeShift.md, content/en/wallets/ShapeShift.md, content/es/wallets/ShapeShift.md, content/fr/wallets/ShapeShift.md, content/no/wallets/ShapeShift.md, content/pt-pt/wallets/ShapeShift.md, content/th/wallets/ShapeShift.md, content/zh-tw/wallets/ShapeShift.md
The ["new" logo](https://github.com/dogecoinfoundation/dogecoin.com/issues/306#issuecomment-2397657303) was only updated in Chinese (China) in #307, this fixes it in all languages.
=> fix: shapeshift logo in few languages

content/de/wallets/CoinWallet.md, content/en/wallets/CoinWallet.md, content/es/wallets/CoinWallet.md, content/fr/wallets/CoinWallet.md, content/no/wallets/CoinWallet.md, content/pt-pt/wallets/CoinWallet.md, content/th/wallets/CoinWallet.md, content/zh-cn/wallets/CoinWallet.md, content/zh-tw/wallets/CoinWallet.md
Coin Wallet is a non-custodial multicurrency crypto wallet that supports 17 coins and many tokens, as well as Dogecoin.
It's an open-source wallet, and the code is available here: https://github.com/CoinSpace/CoinSpace
Coin Wallet is available as a web wallet, a mobile wallet (iOS & Android), and desktop apps (Windows, Linux & MacOS).
Website: https://coin.space/
=> Add Coin Wallet to the list
